services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy

    environment:
      - WG_HOST=165.227.12.213
      - PASSWORD_HASH='$2a$12$nGM/Up.caY6VWHCVZl8b7.Zh24GlrMPJaJuFgCCrC9D/jqK/u64xe'
      - WG_PORT=51820

    volumes:
      - ./wireguard:/etc/wireguard:Z

    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1

    restart: unless-stopped
