services:

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=165.227.12.213
      - PASSWORD_HASH=$$2b$$12$$5rJFpRDemdIiOnUhFilQb.TF3gzRyxBMHYCji.v2JvkujAb4/MUNS
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=172.22.0.53
      - WG_ALLOWED_IPS=0.0.0.0/0
    volumes:
      - ./vpn:/etc/wireguard:Z
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      - internal

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    volumes:
      - ./music/data:/data:Z
      - ./music/library:/music:ro,Z
    environment:
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 1h
      ND_EXTAUTH_TRUSTEDSOURCES: 172.22.0.0/24
      ND_EXTAUTH_USERHEADER: Remote-User
      ND_ENABLEUSEREDITING: false
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 172.22.0.10

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./step-ca/certs/root_ca.crt:/etc/caddy/certs/root_ca.crt:ro,Z
    networks:
      internal:
        ipv4_address: 172.22.0.11

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - DOCKER_API_VERSION=1.40
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=daron.valdiviaceron@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=daron.valdiviaceron@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=daron.valdiviaceron@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=ajrs dxov vvfz dsxd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    security_opt:
      - label=disable
    command: --interval 300
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    volumes:
      - ./nextcloud/data:/var/www/html:Z
      - ./music/library:/music:Z
      - ./media/pictures:/media/pictures:Z
      - ./media/videos:/media/videos:Z
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=changeme
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.zharkaron.lab
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - SQLITE_DATABASE=nextcloud
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 172.22.0.12

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    volumes:
      - ./adguard/conf:/opt/adguardhome/conf:Z
      - ./adguard/data:/opt/adguardhome/work:Z
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 172.22.0.53

  step-ca:
    image: smallstep/step-ca:0.27.5
    container_name: step-ca
    dns:
      - 172.22.0.53
    volumes:
      - ./step-ca/config:/home/step/config:z
      - ./step-ca/certs:/home/step/certs:z
      - ./step-ca/secrets:/home/step/secrets:z
    networks:
      internal:
        ipv4_address: 172.22.0.50
    restart: unless-stopped

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      - TRUSTED_AUTH_HEADER=Remote-User
    volumes:
      - ./beszel/data:/data:Z
    networks:
      internal:
        ipv4_address: 172.22.0.20

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    environment:
      - PORT=45876
      - KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINl1Fat5NN1WZlPTNatdd8j++3d95F2zOFxlePWSeq/w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
    networks:
      internal:
        ipv4_address: 172.22.0.21

  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    security_opt:
      - label=disable
    group_add:
      - 990
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./dockge/data:/app/data:Z
      - ./dockge/stacks:/opt/stacks:Z
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_ENABLE_CONSOLE=true
      - DOCKGE_DISABLE_AUTH=true
    networks:
      internal:
        ipv4_address: 172.22.0.22

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - ./homarr/config:/appdata:Z
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
    environment:
      - TZ=UTC
      - SECRET_ENCRYPTION_KEY=678edf0762d2dce8a7a6016c0dad9aa91b19f604a09d75d79c4775c3634acbbe
    networks:
      internal:
        ipv4_address: 172.22.0.30

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    volumes:
      - ./mealie/data:/app/data:Z
    environment:
      - TZ=UTC
      - ALLOW_SIGNUP=false
    networks:
      internal:
        ipv4_address: 172.22.0.31

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
