###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: 6ac55e2d727eebe2e4b6264a5a9ffd8f91f2cbb09e6ae99116b9ba1222796658

default_redirection_url: http://homepage.zharkaron.lab

totp:
  issuer: zharkaron.lab
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: authelia.zharkaron.lab
      policy: bypass
    - domain: "*.zharkaron.lab"
      policy: bypass
      networks:
        - 10.8.0.0/24
    - domain: "*.zharkaron.lab"
      policy: one_factor

session:
  name: authelia_session
  secret: ebc24c1af501b9875c229149f559ce746648fe35d52609fc21611bd98ff56de8
  expiration: 24h
  inactivity: 2h
  remember_me: 30d
  cookies:
    - domain: zharkaron.lab
      authelia_url: http://authelia.zharkaron.lab
  redis:
    host: authelia-redis
    port: 6379
    database_index: 0
    maximum_active_connections: 10

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: 728993c594cfd1ef2cb0e4ee39a181d9b20e04282d604fd28a1b9a0e73a7108e
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notifications.yml
